import './startup-qr-reset.js'
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './App.css'
import './v2.css'
import './final-dashboard-fixes.css'
import './dashboard-recent-obtained.css'
import './dashboard-remove-nearest.css'
import './dashboard-highlights-static.css'
import './dashboard-button-labels.css'
import './visual-report-print-fit.css'
import './visual-report-safe-margin.css'
import './visual-report-order-switch.css'
import './editing-controls.css'
import './album-code-labels.css'
import './sticker-tone-fixes.css'
import './qr-trade.css'
import './qr-camera-fixes.css'
import './qr-compact-match-fixes.css'
import './manual-trade-lock-feedback.css'
import './qr-owner-profile.css'
import './qr-runtime-fixes.js'
import './qr-match-selection.js'
import './manual-trade-lock-feedback.js'
import './qr-owner-profile.js'
import './dashboard-highlights-static.js'
import './trade-default-qr.js'
import './panini-logo-pixels.css'
import './header-logo-svg.js'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
